{% set name = "knewstuff" %}
{% set version = "5.65.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/knewstuff-{{ version }}.tar.xz
  sha256: 0ec8ab4d7f52c94fb479c0c56ed762748832c76e88b495694b7485e79d9797d9

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('knewstuff', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - attica
    - kio
    - ki18n
    - kconfig
    - kxmlgui
    - kconfig
    - karchive
    - kservice
    - kcoreaddons
    - kcompletion
    - kiconthemes
    - kitemviews
    - ktextwidgets
    - kwidgetsaddons

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5NewStuff.so

about:
  home: https://api.kde.org/frameworks/knewstuff/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: 'Framework for downloading and sharing additional application data'
  description: |
    The KNewStuff library implements collaborative data sharing for applications.
    It uses libattica to support the Open Collaboration Services specification.
  dev_url: https://cgit.kde.org/knewstuff.git/tree

extra:
  recipe-maintainers:
    - scopatz
