{% set name = "knewstuff" %}
{% set version = "5.79.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/knewstuff-{{ version }}.tar.xz
  sha256: 3e2055002f7e2f8cbffb414b7cd98ed38b911b95d5eee914139389a041064f2f

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('knewstuff', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - attica >={{ major_minor }}
    - kio >={{ major_minor }}
    - ki18n >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - kxmlgui >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - karchive >={{ major_minor }}
    - kservice >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
    - kcompletion >={{ major_minor }}
    - kiconthemes >={{ major_minor }}
    - kitemviews >={{ major_minor }}
    - kpackage >={{ major_minor }}
    - ktextwidgets >={{ major_minor }}
    - kwidgetsaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5NewStuff.so

about:
  home: https://api.kde.org/frameworks/knewstuff/html/index.html
  license: GPL-2.0-only AND GPL-3.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-GPL AND LicenseRef-KDE-Accepted-LGPL
  license_file:
    - LICENSES/GPL-2.0-only.txt
    - LICENSES/GPL-3.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-GPL.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Framework for downloading and sharing additional application data
  description: |
    The KNewStuff library implements collaborative data sharing for applications.
    It uses libattica to support the Open Collaboration Services specification.
  dev_url: https://cgit.kde.org/knewstuff.git/tree

extra:
  recipe-maintainers:
    - scopatz
